name: pair_up
description: "Pair Up - A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

  # Navigation
  go_router: ^14.2.7

  # Dependency Injection
  get_it: ^7.6.4


  # Utils
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting
  flutter_lints: ^5.0.0
  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/
    - assets/app_logo.png
    - assets/icons/
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true
